CREATE TABLE ROLES
(
    ID   INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE USERS
(
    ID         INTEGER AUTO_INCREMENT PRIMARY KEY,
    ROLE_ID    INTEGER NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    EMAIL      VARCHAR(255) NOT NULL,
    PASSWORD   VARCHAR(255) NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);

-- Inserting data

INSERT INTO ROLES (NAME)
VALUES ('ADMIN'),
       ('TRENER'),
       ('KORISNIK');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, PASSWORD, ROLE_ID, EMAIL)
VALUES ('Pero', 'Peric', 'test', SELECT ID FROM ROLES WHERE NAME = 'KORISNIK', 'pero@gmail.com');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, PASSWORD, ROLE_ID, EMAIL)
VALUES ('Jura', 'Juric', 'test', SELECT ID FROM ROLES WHERE NAME = 'KORISNIK', 'jura@gmail.com');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, PASSWORD, ROLE_ID, EMAIL)
VALUES ('Zdravko', 'Zdravic', 'test', SELECT ID FROM ROLES WHERE NAME = 'TRENER', 'zdravko@gmail.com');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, PASSWORD, ROLE_ID, EMAIL)
VALUES ('Luka', 'Lukic', 'test', SELECT ID FROM ROLES WHERE NAME = 'ADMIN', 'luka@gmail.com');
